parse and display results output

diff --git a/.github/workflows/pr_checklist.yml b/.github/workflows/pr_checklist.yml
--- a/.github/workflows/pr_checklist.yml
+++ b/.github/workflows/pr_checklist.yml
@@ -36,8 +36,38 @@ jobs:
           echo "EOF" >> $GITHUB_ENV
 
       - name: Call PR Checklist
+        id: pr-checklist
         uses: ./.github/actions/pr-checklist
         with:
           files-changed: ${{ env.FILES_CHANGED }}
           files-required: "^pyproject.toml$"
           files-optional: "^README.md$__I__^docs/.*__I__^CHANGELOG.md$"
+
+      - name: Report results
+        run: |
+          missing=${{ steps.pr-checklist.outputs.missing }}
+          skipped=${{ steps.pr-checklist.outputs.skipped }}
+          found=${{ steps.pr-checklist.outputs.found }}
+          echo "# PR Checklist" >> $GITHUB_STEP_SUMMARY
+          echo "" >> $GITHUB_STEP_SUMMARY
+          while read -r line; do
+            if [[ -z $line ]]; then
+              continue
+            fi
+            echo "- :x: Missing $line" >> $GITHUB_STEP_SUMMARY
+          done < <(echo $missing | sed 's/__I__/\n/g')
+          while read -r line; do
+            if [[ -z $line ]]; then
+              continue
+            fi
+            echo "- :eyes: Skipped $line" >> $GITHUB_STEP_SUMMARY
+          done < <(echo $skipped | sed 's/__I__/\n/g')
+          while read -r line; do
+            if [[ -z $line ]]; then
+              continue
+            fi
+            echo "- :white_check_mark: Found $line" >> $GITHUB_STEP_SUMMARY
+          done < <(echo $found | sed 's/__I__/\n/g')
+          if [[ -n $missing ]]; then
+            echo "::error::Required files were not found."
+            exit 1
